fh1=open("output.txt","wt")
data=input("Enter text to write to the file:")
fh1.write(data)
fh1.write("\n")
print("Data successfully written to output.txt")
fh1.close()
print()
fh2=open("output.txt","a+")
Add_data=input("Enter additional text to append to the file:")
fh2.write(Add_data)
print("Data successfully appended")
print()
fh2.seek(0)
print("Final content of output.txt:")
for line in fh2.readlines():
    print(line,end="")
fh2.close()
